app = "trading-bot-api"
primary_region = "fra"   # Frankfurt -- Turkiye'ye en yakin

[build]

[env]
  AUTO_START = "true"

[http_service]
  internal_port = 8080
  force_https   = true
  auto_stop_machines  = false   # Asla uyuma!
  auto_start_machines = true
  min_machines_running = 1      # Her zaman en az 1 makine calissin

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
